# Generated by Django 3.0.5 on 2020-05-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_eduImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=30, unique=True)),
                ('image_path', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('device_id', models.CharField(max_length=30)),
            ],
        ),
    ]
